language: bash
services:
- docker
script:
- cd app
- "./gradlew pushDockerImages"
true:
  branch: master
env:
  global:
  - secure: C5heeeqPkDqLyebuC+iH0QWy06hx9gNe64wlb6cfgkQrhqNlzJ2lJfdT7ZLBLZf5qKvacEpDpNdEcirCl3xiK6VWBvNzBoEzBmmPl8Z6jWdxBvYUORe8wQGhTgEP7bifOOxqkwKpaowsMS6d03Ov+Vr2yTyoVpKr1hUgtWDnRu5KFZ1Xxe1ABfRRg+TLOK5B87OrS2myIIVCxMCaHY0snVgNLhsvJclplpAmOiBtXWqNoHpjhFGcksNp0uMaU3FHbp+a74PfESwcdEjkLw3pAC8nZm5hvUUNxzkl2ip6HV4iI5DKaNVLNBhXYgILVUaRd0XQZaquWMLo2HC7lLKJRWNfvu2FlEbtoryLe761HjhUQQJS+JuNqPj94tnYay5eied1jkMzzrdnsfjoqw7LN6jAtg6stguMlI/ycnPGVhKXOTCHmfWVqcw7zGhL+jPtU5jcUStI4syst3kGCa9ym/6ZZJ3Gdd7mVqiJlOXYe4hPZV1ITxafh5pQ4C4sVWny6IZAVGSDa+1z+cTLIshnc5fcWTLCSqQ+8Wz1px1x4ARnc3yBisPVormdAzVBRMg9eEoXftqFuJM9qlVi0LxBQJmyDq8yQbQi+0zoiVLzcTCjjaC2BbbuQd01NlKvoGAn4O3mQkldPh7BhAubx2pY06R33sT7ZzVRU9/X0x7UOaA=
  - secure: 0Vd5IlhfQBu1fS6Hj6sAOoRNZ01nltPPslqKxnkVVV3+/KfblwRCa6RoE5cZkHQRBMT0l+Ydnl4hEDE0apRsBrJVNgROmhHB2X2YsHGhcVqrCDyX98mVs4/aaUMEYn3MiT80Wzzl7frceqT0hFfhAqD0M8YZTBBeAnJTuY0F4U0lGr79+pGrqsHxAV2ARAtyzSJxvVvi47+h7f/1iM5srvnpy/092hTOe2hbm2vVYYxHOAtJLqauMHt9dhhEXkEdvW8BuiaPvnl8EIzqsrJNvKonu7OO7rZTLLPVGxuanP9YIqRJcoH3PigtZrNrOikpkN2q/2E2ptOg24CFXKfhDcCrTn3kWxTZh5fcLhxmv0qymt6Dv2BDSXMXioaKGhH0E8OAoCLSr3HfF4mK8Bcx5gT8PbBCisgEzY6wSnv+mfIxZa2N9g1gjt64RxG4JAp/9sLTW7JdcGlcTiHVketu0CKRF2bngT69MFH+G0yyw3akRBYcL8FAs8223qono2xeIcunUvyXjgrX48QVwuY2Xdm9dY3CQ5NUdNgDfJJTT2BNmEEUoFDfg+0l/ggndEHnuMq24hl1Sqm3Y80kkDe3sJibLveLM1MDMUyHHZFexPwLcDYz9Y/OF0tn0EUBF4l0rdhcrxDl9cyMdbHBampvkvYIT+Ie/QZfVrx4uqpJD4Q=
