language: bash
services:
- docker
script:
- cd app
- "./gradlew pushDockerImages"
true:
  branch: master
env:
  global:
    secure: "Rhjm1Y9KrcRnW7Bthz5zwVw9VvOnsbbvn+HMh+i393Mabrc0X+AG9SA4G8IS2PwcUyAIUVAtc0lDneDvzRkg9is6aZvbiEK9hGEQfs8NO+79bCYN0PYHmEcRiXnGgY5769eMn8sQsiCn76W9CZE6+emlz33kaJjkE5HZJV5hGm9cmPN7OOiGmIPFTaGjRgu+c1dlxFdJOPxIvbxs4rBGRt6w9GIC5uEmHyaX+o4iMTrX5TZxAN87wGTwuAwZKV3OCrXHqWGM2LUdDEVkbsMEf+P4ePYRA9Rijt5RbTavUytdAcMyCRJf3VDvl0ZOwpJMn9ZIhVRwhSM7ru8KoAarsvfM+n3ajh/5oBmC0+P6Cuf6hk/5ncNsmXWpp+0V1R/4+utm59lQRVkPwJguILc/tNAAvG2Hca3KzlVCyqaVjad4/Kl9BB1IuvLf2z0MidMwTmhqv3Nvh1JznLE5s0uJ2Onl67BxIL93lqnLYggiDGCBXbYmRdsIASaHirccxH5sV3YyN1PyykoCxx04Y4qdndv8UySCocLiQH0nOaBiOkHU0kHL+7W+quZkXUgIxHvS7uhXqUuM9uhfvtxJUa10GOc6RX4cFE/AOmVfuthce76vZ2QXGuudby8Cu0OZEzFKEYUk4tJWTY8na1I45ZkMLJrAasr4EEO+gHLRYE/VU9c="
    secure: "PTsh/KhwbYquI/zBdTg4tcdLuDw1R8snpovhwGcgeFzqHiFWZdWqWRsCq/FnLPWdsL/jZmWOrpfpTYGB6NNRJwMXb1h/spI8kb3kxvWKJLIDqwjC1Obk14tpGVlKsms3BqI+huMR733aUX6BTfVJ36ucgGJ/KeBbuUnbR5Fm+y1UCvQV8Ca+Y0IBknwoJ4pX95InieIKQ7YT0ae9yLPj4Ev+LZJFYG3bob5JK4mLCM3xEfjyfg4mp7n+QIbzZO5pyE75a8X+5iBVjGQYdva1RqmT+72w9isHIKeOooXuIsBKQqTszWf5ZL4LVPs+/grXb/gTE8vggIaoYJLKwyQfe/5LXu3Gs4DIO1L9r/4eGFzcM3PQAWTN2BYzQ7oxuUtakEmxPkyF2nZGXQXukrtfQhjNSagk2akAPsY20jvT3gn5ouIVzNe2iDMIj6H3Ptmn43bfi72yfcwIZv2MwHRU/y4JR54mD5dmCR5mBxzE8C+N9QWkC6m9LPC1LTF21tBA9n7d+iUQxu+a9udry9EmDhrK/wTQEcObFkQOXEmfiIv9139Q8tNFmTAxN9090N6w+KDYQd1QFax4aZpxUTgXc6eFuAN2Vwvda9v9YlTCa6N78OkV0ahJnbWk6Gg2DTWOse11VDkclBhSd8C5jtWz+FoIrsW+ULpU73DWEVYuBAw="
