apiVersion: v1
kind: Service
metadata:
  name: tbz-deployer
  labels:
    app: tbz-deployer
spec:
  type: LoadBalancer
  ports:
    - port: 7000
      protocol: TCP
  selector:
    app: tbz-deployer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tbz-dployer-deployment
  labels:
    app: tbz-deployer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tbz-deployer
  template:
    metadata:
      labels:
        app: tbz-deployer
    spec:
      containers:
        - name: tbz-deployer
          image: nliechti/tbz_deployer:2
          ports:
            - containerPort: 7000
              name: tbz-deployer
          env:
            - name: EMAIL_SMTP_SERVER
              value: "smtp.gmail.com"
            - name: EMAIL_SMTP_PORT
              value: "587"
            - name: EMAIL_SMTP_USER
              value: "nliechti@gmail.com"
            - name: EMAIL_SMTP_PASSWORD
              value: "parlefeiewlzqtmh"
            - name: KUBERNETES_MASTER_URL
              value: "https://192.168.64.4:8443"
            - name: KUBERNETES_CLIENT_CERT_DATA
              value: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBRENDQWVpZ0F3SUJBZ0lCQWpBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRFNU1URXhPVEV6TURNME5Gb1hEVEl3TVRFeE9URXpNRE0wTkZvd01URVhNQlVHQTFVRQpDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGakFVQmdOVkJBTVREVzFwYm1scmRXSmxMWFZ6WlhJd2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFES3MxMm9YR2x6QlBCeUZPUzFMeHJiSEVlS1ZBUkIKcWdGZUl6U3l3SDRpZmY1b09ZWG1MRnE4M3UwNW85NVNVYWhnYVRFejZiME4rWm5IcDhYaXRIaU9HM1pVSjQ5TQp5LytjdGJTYzVlTzdzRmppc0tiME81bXRhWFJaWUM3QXJBeFdaWXoySEJVNDltQ09aMWtpQWk0SG11a3dENE1ECmRha1ByZzYxcGUxR01Id3YvLzlKcmZGcXBlWlhoRmJ5MWd5cmowVXJmV0ZiMERYUzZrVjcxem5EOENlM0xoSkoKVmVRM3B4enZSRXcrN2FWYTV4V2VpcmxOSDdtN3pYZ1JsZEc3V1FIeEJZKzI2N0NPaGQ1QnFYeU1adXRMaUR1OQoxM1lDZzBoVWQ0WDBxMm5IT05GcXF3OTFkeVArSmlpY1YwZlo0b0psdTcxZCt1WmZuKy9GSVlrVkFnTUJBQUdqClB6QTlNQTRHQTFVZER3RUIvd1FFQXdJRm9EQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBUVVBTmR5eXgvQXBpNkY2Nwo3VlNyZDNPOU82Nkk5V1ltVXpzdWprV1U5elNiODFqYWhmY1REMWtTbUtBOFFmMmgvREhzbE5BZjhYMUNSZ0pMCkk0YkpZekw1VlFmLzBTUTVzemgyM09yNUJJM0Jnd2RBQlI3TS9ya3prcEdGbEtBaDZFcmVtNTJ3dVVLZE9jVlgKUDdSckJyZVpQenZMekZ3WXlUazJrbWYvVi9yRnY4LzJmZUlmVHdZdE1vVzFyREdCMGZQYzhRdzZlK2wvb3E0YgpXdG5tUDJxUFZHaXVsTDlOZzlHUDM1QkFvd2c2eGF3ejJ5aFQvMzYvWnQ3VFpsam1xR3V5cDlIeHFKeUU1VTNUClhEb21PbG1ITWw3S05vRk9aRmVRSmhkWjlNRU5QdmlRckErYUpGTFhLb2t0ZGFxUE9rUjBTai8zbVBLcWJpKzgKZU8zMm5nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ=="
            - name: KUBERNETES_CLIENT_KEY_DATA
              value: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBeXJOZHFGeHBjd1R3Y2hUa3RTOGEyeHhIaWxRRVFhb0JYaU0wc3NCK0luMythRG1GCjVpeGF2Tjd0T2FQZVVsR29ZR2t4TSttOURmbVp4NmZGNHJSNGpodDJWQ2VQVE12L25MVzBuT1hqdTdCWTRyQ20KOUR1WnJXbDBXV0F1d0t3TVZtV005aHdWT1BaZ2ptZFpJZ0l1QjVycE1BK0RBM1dwRDY0T3RhWHRSakI4TC8vLwpTYTN4YXFYbVY0Ulc4dFlNcTQ5RkszMWhXOUExMHVwRmU5YzV3L0FudHk0U1NWWGtONmNjNzBSTVB1MmxXdWNWCm5vcTVUUis1dTgxNEVaWFJ1MWtCOFFXUHR1dXdqb1hlUWFsOGpHYnJTNGc3dmRkMkFvTklWSGVGOUt0cHh6alIKYXFzUGRYY2ovaVlvbkZkSDJlS0NaYnU5WGZybVg1L3Z4U0dKRlFJREFRQUJBb0lCQUJkK2FxQ1U5WFByWXFNVwpZTnZQTmVHbmlYTXpBYnRLcFJYd0pxK0JPQjF2VlFsbmdXbUlRb3dabW8xUHZQajFsZnAydHNrNWtqd0liaGFDCkQ2R1RJVlgzUU9QSUlnZllyU3ZRczdwcnV0V0tQd01uVG5LSVpldC9pWWpDYVNqVHlDcExZdWN6b2hJVUhHVGsKL2FPL2RPNVV1aXBqNGQrSXg2dVZsUWJnMEh1TjlrZ2dibkRHMXNYckhqekZ3TU1XL0RNOUgzWkE1NW5tbzVyYQpQZXBXby9xcis3VCtLZkRHcnFabEpmb3NoVjV1L2xydHEzV0V6eCszMXF2RURHS3h6ZTY5ekZJLzNUd3dNbEZKCld4MWNOVC91dmdpdk8zd1E2elpKeVRITmZJSFN6QmMvd3JlM201bC82MlUxNEpOMzl5cXo2SmhQVTBkaGcwSHkKZWV1VzRnRUNnWUVBNWJYYjhoWWtIY2VzUzMrOWNRSW5PRlRiT3NQRUpUMnhnWHhHZzVTMFBGWXRrQVhmQW5wRwpMTzlLZlZNa2tUUUtqNCtCQVBTZElwaUdoOHlHOElRamtYV2E3QUZXMW9RelZoZStvMHEyOXg2MkI2UGNtRGprCkxDcnhaSHRsOEpJQjZkZU9ObTN2VFd5V3VoUXNKcjRndmt5ODkvTXYrQTV4TVdhaHAyZGQzN1VDZ1lFQTRlWXEKVFE4N1lqemNuYTF5bDNRaENSdS9hSVdqZCtDMDl1SWFmMG5NR0hzYmZFc3lQN09LSkFsSFQ3RVIzR0FTeDgrVApzem1meUc2SWlINmVqY3ZKMnVEcVZaQmQvYTNBVzM0Um9YWTZqaSt0L2ZZNGdkZE41MU1GS3dwUlo1THlYY0xICnl0eVNJQmZiUXNnWTBXMDUwWlZtclRoeVRsR3JET0t4Q3RNRkgrRUNnWUVBeWVUeUlLOUhKUWwzTEpCa2I2dmwKenNQK1A0TUtwWFM0eThidnJ2eUhBVFQ1TE1tTVBZQThwNGZWMzVxdzNCSnlhY1ZHTEJIUy9qSXlvNjZtdDBSYwpncDlyLzV3WnQ4ZFAyNDVaRnVvM0w3SEZhYWVpM2dPNnYvc3FXUmQvL0ZaSDZrQnpsUEZBejdydUt6UkpyZStUCmxjNmFsQThoRFJPY2R6L3VPdFZHRTdVQ2dZQm9hYzZibDdMSEVZS1hqeGdzVVEwRC9NTllPSXo2Vis3TlBtMG8KOEo5Wm9XMXU0Z0x6MXJTL08xcXV4eFdPV3duVE9XcjNxR2JtYWRESjVseTdCYnJqWkpwcnVqTDNrbHdhN2dhUQpMdW1aMXdnQkh0RzNraUQ4RHkrUVdWQ1BJeWpMbGNCclQ5QnE3UnYzbmkxNmY1WDkvYVJiNUg5UkhBYUlDaS95CjVONjFnUUtCZ1FEa0dVa1pLbDdtbnpLTWtJMHNuYmdqL1Y2VDliSUlDak04TmxUenBRVWN2Ykp4Wi9nRXBYSEgKQTZaSDlzMkZGTkRaVzhtV0p6WXpOeWhDK3RTVWhDSmZWbHdUUUQvV1l0L1lQYVBLWTRJZm8yNVFuV3RXY1M2cQovM2hxMUFUTUxjaDhYNURKck5RdTd0b3F4REJoSE41NDY2ZnltZEh5QTdQdHF6ZFZkOVEwaUE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ=="
              
